---
title: "Hershberger 690 Homework 3"
format: html
editor: visual
---

```{r}
library(readxl)
data <- read_excel("~/ncesdata_MASS_202425 (1).xlsx")
View(data)
head(data)
str(data)
```

You can add options to executable code like this

```{r}
library(ggplot2)

ggplot(ncesdata_MASS_202425_1_, 
       aes(x = reorder(`County Name`, `County Name`, length))) +
  geom_bar(fill = "steelblue") +
  coord_flip() +
  labs(title = "Number of Schools by Massachusetts County",
       x = "County",
       y = "Number of Schools") +
  theme_minimal()
```

```{r}
ncesdata_MASS_202425_1_$`Student Teacher Ratio` <- as.numeric(gsub(",", "", ncesdata_MASS_202425_1_$`Student Teacher Ratio`))
```

```{r}
library(dplyr)


county_avg <- ncesdata_MASS_202425_1_ %>%
  group_by(`County Name`) %>%
  summarise(avg_ratio = mean(`Student Teacher Ratio`, na.rm = TRUE)) %>%
  arrange(desc(avg_ratio))
```

```{r}
library(ggplot2)

ggplot(county_avg, aes(x = reorder(`County Name`, -avg_ratio), y = avg_ratio)) +
  geom_col(fill = "red") +
  labs(title = "Average Student to Teacher Ratio by County",
       x = "County",
       y = "Average Student–Teacher Ratio") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
